### ISSUE TITLE
Adhere to Android Kotlin Style Guide

### ISSUE THREAD

**Issue by vincent-paing** [myolwin00/Sunshine-android#1]
[Kotlin Style Guide](https://android.github.io/kotlin-guides/style.html#non-constant-names) does not recommend usage of Hungarian notation. 

> Non-constant names are written in camelCase

Moreover, it creates weird looking syntax when used together with Kotlin property access.

**Comment by myolwin00** [comment]
Sry for late.
I will update it later. 
I hate that too :3

**Comment by myolwin00** [comment]
fixed.
